---

- name: Install list of packages - yum
  yum: name={{item}} state=installed state=latest
  with_items:
       - unzip
       - python-pip

- name: Install list of packages - pip
  pip: name={{item}} state=installed state=latest
  with_items:
       - awscli
       - boto3

- name: set-environment
  include: environment.yml

