---

- name: Install iptables-services
  yum:
    name: iptables-services
    state: latest

- name: Enable iptables-services
  service:
    name: iptables
    enabled: yes

- name: Enable MASQUERADE
  iptables:
    table: nat
    chain: POSTROUTING
    jump: MASQUERADE

- name: Save iptables state
  command: service iptables save

- name: Enable ip forwarding in sysctl
  sysctl:
    name: "net.ipv4.ip_forward"
    value: 1
    sysctl_set: yes
