---
- hosts: all
  become: yes
  vars:
  pre_tasks:
    - name: gather ec2 facts
      action: ec2_facts
      tags:
        - always
  roles:
    - common
    
- hosts: nat 
  become: yes
  roles:
    - nat

- hosts: bastion
  become: yes
  vars:
    - consul_atlas_join: true
    - consul_atlas_infrastructure: "acme/sandbox"
  roles:
    - bastion

- hosts: consul 
  become: yes
  vars: 
    - consul_server: true
    - consul_web_ui: true
    - consul_bootstrap_expect: 3
    - consul_with_dnsmasq: true
    - consul_atlas_join: true
    - consul_atlas_infrastructure: "acme/sandbox"
  roles:
    - consul

- hosts: nomad 
  become: yes
  vars: 
    - consul_atlas_join: true
    - consul_atlas_infrastructure: "acme/sandbox"
    - nomad_server_enabled: true
    - nomad_server_bootstrap_expect: 3
  roles:
    - consul
    - nomad
