---
- hosts: all
  become: yes
  pre_tasks:
    - name: gather ec2 facts
      action: ec2_facts
      tags:
        - always
  roles:
    - common
    
- hosts: nat 
  become: yes
  roles:
    - nat

- hosts: bastion
  become: yes
  roles:
    - bastion

- hosts: consul 
  become: yes
  vars: 
    - consul_server: true
    - consul_atlas_join: true
    - consul_web_ui: true
    - consul_with_dnsmasq: true
    - consul_bootstrap_expect: 3
    - consul_atlas_infrastructure: "acme/sandbox"
  roles:
    - consul
