---
- hosts: all
  become: yes
  vars:
  pre_tasks:
    - name: gather ec2 facts
      action: ec2_facts
      tags:
        - always
  roles:
    - common
    
- hosts: nat 
  become: yes
  roles:
    - nat

- hosts: bastion
  become: yes

- hosts: consul
  become: yes
  vars: 
    - consul_server: true
    - consul_web_ui: true
    - consul_with_dnsmasq: true
  roles:
    - consul

- hosts: nomad
  become: yes
  vars: 
    - nomad_server_enabled: true
    - consul_with_dnsmasq: true
  roles:
    - consul
    - nomad

- hosts: worker
  become: yes
  vars:
    - consul_with_dnsmasq: true
  roles:
    - consul
    - nomad
    - docker
