---
- include: install.yml
  tags:
    - install

- name: Configure nomad agent (base) 
  template: src=base.hcl.j2 dest=/etc/nomad/conf.d/base.hcl
  tags:
    - configure

- name: Configure nomad agent (server) 
  template: src=server.hcl.j2 dest=/etc/nomad/conf.d/server.hcl
  tags:
    - configure

- name: Copy nomad advertise conf generator
  copy: src=generate_advertise.sh dest=/usr/local/bin owner=root group=root mode=0755

- meta: flush_handlers
